language: go

go:
    - 1.10.x

jobs:
    include:
        -   stage: build
            env:
                - DEP_VERSION="0.5.1"
            before_install:
                - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
                - chmod +x $GOPATH/bin/dep
            install:
                - dep ensure
            script:
                - pwd
                - ls -la .
                - go build -i "-ldflags=-linkmode internal" -o ./sbh github.com/mihard/selective-build-helper
            deploy:
                provider: releases
                skip_cleanup: true
                api_key: $GITHUB_TOKEN
                file: sbh
                on:
                    tags: true
                    branch: master